name = "mps"
uuid = "dc2f018a-7bfa-46fa-83ce-8b0d7b4797e5"
authors = ["Niklas Bliemel <niklas.bliemel@stud.uni-regensburg.de>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
IJulia = "1.29.0"
Plots = "1.40.16"
QuanticsTCI = "0.7.1"
TensorCrossInterpolation = "0.9.17"
